In [1]:
import pandas as pd
import numpy as np

In [10]:
cgmap_file = "/home/wbguo/iproject/BSReadSim/temp/data/sim.CGmap.gz"
asm_file   = "/home/wbguo/iproject/BSReadSim/temp/data/sim.asm.gz"

In [3]:
df = pd.read_csv(cgmap_file, compression='gzip', header=None, sep='\t', quotechar='"')

In [4]:
df

            0  1       2    3   4         5   6   7
0       chr10  G    4950   CG  CG  1.000000  10  10
1       chr10  G    4957  CHH  CT  0.000000   0  13
2       chr10  G    4963  CHG  CA  0.000000   0  13
3       chr10  G    4964  CHH  CC  0.000000   0  13
4       chr10  G    4966  CHH  CT  0.000000   0  13
...       ... ..     ...  ...  ..       ...  ..  ..
459342  chr14  C  350768   CG  CG  0.916667  11  12
459343  chr14  C  350776  CHH  CT  0.000000   0  13
459344  chr14  C  350786  CHH  CC  0.000000   0  12
459345  chr14  C  350787  CHH  CA  0.916667  11  12
459346  chr14  C  350789  CHH  CT  0.000000   0  12

[459347 rows x 8 columns]

In [5]:
df[6] = 'snp_pos'
df[7] = "ref"
df[8] = "alt"
df[9] = df[5]
df[10]= df[5]
df[11]= np.exp(np.random.rand(df.shape[0]) - 0.5)
df[12]= 'p_val'
df[13]= 'comment'

In [6]:
df[9] = df[5]*2/(1+df[11])
df[10]= df[5]*2*df[11]/(1+df[11])

In [7]:
df2 = df.loc[(df[9] <1) & (df[10] < 1) & (df[5] >0),:]

In [8]:
df2

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
38,chr10,C,5077,CHH,CA,0.066667,snp_pos,ref,alt,0.071772,0.061562,0.857737,p_val,comment
41,chr10,C,5090,CHG,CT,0.083333,snp_pos,ref,alt,0.099090,0.067576,0.681973,p_val,comment
47,chr10,C,5103,CHG,CT,0.083333,snp_pos,ref,alt,0.089057,0.077609,0.871461,p_val,comment
50,chr10,C,5107,CG,CG,0.636364,snp_pos,ref,alt,0.620668,0.652060,1.050579,p_val,comment
61,chr10,G,5174,CHH,CT,0.083333,snp_pos,ref,alt,0.067449,0.099217,1.470991,p_val,comment
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
459270,chr14,C,350383,CHH,CC,0.083333,snp_pos,ref,alt,0.091865,0.074801,0.814247,p_val,comment
459271,chr14,C,350384,CHH,CC,0.076923,snp_pos,ref,alt,0.078556,0.075290,0.958416,p_val,comment
459297,chr14,C,350501,CHH,CT,0.090909,snp_pos,ref,alt,0.082640,0.099178,1.200116,p_val,comment
459300,chr14,C,350509,CHG,CA,0.142857,snp_pos,ref,alt,0.141516,0.144198,1.018957,p_val,comment
459342,chr14,C,350768,CG,CG,0.916667,snp_pos,ref,alt,0.925423,0.907911,0.981077,p_val,comment

In [12]:
df2.to_csv(asm_file, index=False, header=None, compression="gzip", quoting=None, sep='\t')