In [1]:
import pandas as pd
import numpy as np

In [2]:
cgmap_file = "/home/wbguo/iproject/BSReadSim/test/data/sim/pe_d/sim.CGmap.gz"
asm_file   = "/home/wbguo/iproject/BSReadSim/test/data/sim/pe_d/sim.asm.gz"

In [3]:
df = pd.read_csv(cgmap_file, compression='gzip', header=None, sep='\t', quotechar='"')

In [4]:
df

            0  1       2    3   4    5  6  7
0       chr10  C    4750  CHH  CT  0.0  0  1
1       chr10  C    4752  CHH  CC  1.0  1  1
2       chr10  C    4753  CHH  CC  0.0  0  1
3       chr10  C    4754  CHH  CA  0.0  0  1
4       chr10  C    4756  CHH  CT  0.0  0  1
...       ... ..     ...  ...  ..  ... .. ..
852124  chr14  G  350996  CHH  CT  0.0  0  1
852125  chr14  G  350997  CHH  CC  0.0  0  1
852126  chr14  G  351000  CHG  CT  0.0  0  1
852127  chr14  G  351014  CHH  CA  0.0  0  1
852128  chr14  G  351018  CHG  CT  1.0  1  1

[852129 rows x 8 columns]

In [5]:
asm_df = df.loc[:,[0,1,2,3,5]]
asm_df.columns = ['chr_id', 'base', 'pos', 'context', 'meth']
asm_df[['ref_meth', 'alt_meth', 'snp_pos','ref|alt','count','p_val']] = pd.DataFrame([[np.nan]*6], index=df.index)

# will not be output
asm_df['tmp'] = np.exp(np.random.rand(df.shape[0]) - 0.5)
asm_df['ref_meth'] = asm_df['meth']*2/(1+asm_df['tmp'])
asm_df['alt_meth'] = asm_df['meth']*2*asm_df['tmp']/(1+asm_df['tmp'])
asm_df['snp_pos']  = 1000             #"snp_pos"
asm_df['ref|alt']  = 'A|G'         #"ref|alt"
asm_df['count']    = '10,10,10,10' #"ref_met,ref_tot,alt_met,alt_tot"
asm_df['p_val']    = 0.05

In [6]:
keep_col = ['chr_id', 'base', 'pos', 'meth', 'ref_meth', 'alt_meth', 'snp_pos','ref|alt','count','p_val']
asm_df2  = asm_df.loc[(asm_df['ref_meth'] <1) & (asm_df['alt_meth'] < 1), keep_col]

In [7]:
asm_df2

,chr_id,base,pos,meth,ref_meth,alt_meth,snp_pos,ref|alt,count,p_val
0,chr10,C,4750,0.0,0.0,0.0,1000,A|G,"10,10,10,10",0.05
2,chr10,C,4753,0.0,0.0,0.0,1000,A|G,"10,10,10,10",0.05
3,chr10,C,4754,0.0,0.0,0.0,1000,A|G,"10,10,10,10",0.05
4,chr10,C,4756,0.0,0.0,0.0,1000,A|G,"10,10,10,10",0.05
5,chr10,C,4758,0.0,0.0,0.0,1000,A|G,"10,10,10,10",0.05
...,...,...,...,...,...,...,...,...,...,...
852123,chr14,G,350993,0.0,0.0,0.0,1000,A|G,"10,10,10,10",0.05
852124,chr14,G,350996,0.0,0.0,0.0,1000,A|G,"10,10,10,10",0.05
852125,chr14,G,350997,0.0,0.0,0.0,1000,A|G,"10,10,10,10",0.05
852126,chr14,G,351000,0.0,0.0,0.0,1000,A|G,"10,10,10,10",0.05
852127,chr14,G,351014,0.0,0.0,0.0,1000,A|G,"10,10,10,10",0.05

In [8]:
asm_df2.to_csv(asm_file, index=False, header=None, compression="gzip", quoting=None, sep='\t')