In [1]:
import pandas as pd
import numpy as np

In [4]:
cgmap_file = "/home/wbguo/iproject/BSReadSim/test/data/sim/pe_d/sim.CGmap.gz"
asm_file   = "/home/wbguo/iproject/BSReadSim/test/data/sim/pe_d/sim.asm.gz"

In [5]:
df = pd.read_csv(cgmap_file, compression='gzip', header=None, sep='\t', quotechar='"')

In [6]:
df

            0  1       2    3   4    5  6  7
0       chr12  C       4  CHH  CC  1.0  1  1
1       chr12  C       5  CHH  CA  0.0  0  1
2       chr12  C       7  CHH  CT  0.0  0  2
3       chr12  G      10  CHH  CA  1.0  1  1
4       chr12  C      12  CHH  CC  0.0  0  2
...       ... ..     ...  ...  ..  ... .. ..
852124  chr14  G  350996  CHH  CT  0.0  0  1
852125  chr14  G  350997  CHH  CC  0.0  0  1
852126  chr14  G  351000  CHG  CT  0.0  0  1
852127  chr14  G  351014  CHH  CA  0.0  0  1
852128  chr14  G  351018  CHG  CT  1.0  1  1

[852129 rows x 8 columns]

In [7]:
df[6] = 'snp_pos'
df[7] = "ref"
df[8] = "alt"
df[9] = df[5]
df[10]= df[5]
df[11]= np.exp(np.random.rand(df.shape[0]) - 0.5)
df[12]= 'p_val'
df[13]= 'comment'

In [8]:
df[9] = df[5]*2/(1+df[11])
df[10]= df[5]*2*df[11]/(1+df[11])

In [9]:
df2 = df.loc[(df[9] <1) & (df[10] < 1) & (df[5] >0),:]

In [10]:
df2

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
23,chr12,C,74,CHH,CA,0.250000,snp_pos,ref,alt,0.276777,0.223223,0.806506,p_val,comment
38,chr12,C,107,CHH,CC,0.571429,snp_pos,ref,alt,0.466274,0.676584,1.451044,p_val,comment
88,chr12,C,210,CG,CG,0.941176,snp_pos,ref,alt,0.907040,0.975312,1.075270,p_val,comment
89,chr12,G,211,CG,CG,0.625000,snp_pos,ref,alt,0.596832,0.653168,1.094392,p_val,comment
103,chr12,C,232,CG,CG,0.500000,snp_pos,ref,alt,0.535856,0.464144,0.866174,p_val,comment
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
851960,chr14,C,350624,CHH,CC,0.400000,snp_pos,ref,alt,0.457599,0.342401,0.748255,p_val,comment
851975,chr14,C,350645,CG,CG,0.500000,snp_pos,ref,alt,0.594241,0.405759,0.682819,p_val,comment
852015,chr14,G,350766,CHH,CA,0.625000,snp_pos,ref,alt,0.544521,0.705479,1.295595,p_val,comment
852018,chr14,G,350769,CG,CG,0.125000,snp_pos,ref,alt,0.134925,0.115075,0.852876,p_val,comment
852056,chr14,C,350853,CHG,CA,0.250000,snp_pos,ref,alt,0.209363,0.290637,1.388198,p_val,comment

In [11]:
df2.to_csv(asm_file, index=False, header=None, compression="gzip", quoting=None, sep='\t')